### ISSUE TITLE
Run PTY tests in CI

### ISSUE THREAD

**Issue by mxsdev** [stateful/runme#169] opened 2023-03-06 20:54 UTC
The suite of tests dedicated to testing PTY winsize is now failing with the following error:

```
failed to copy from pty to stdout; handled EIO
```

Would be nice to figure this one out so we don't have a mismatch between CI and local testing.

**Comment by adambabik** [comment] 2023-03-06 21:32
Oh, I remember now. I wrote https://github.com/stateful/runme/pull/168#issuecomment-1457025344 but I think the root cause of the failed test was different. This error is handled and there is a description why it might happen:

```go
// Linux kernel returns EIO when attempting to read from
// a master pseudo-terminal which no longer has an open slave.
// See https://github.com/creack/pty/issues/21.
if errors.Is(err, syscall.EIO) {
	c.logger.Debug("failed to copy from pty to stdout; handled EIO")
	return
}
```

**Comment by mxsdev** [comment] 2023-03-06 21:36
@adambabik 

Hmm, gotcha. The failed ci is [here](https://github.com/stateful/runme/actions/runs/4345088254/jobs/7589311239) if you wanna check it out, but the logs seem overall fine.

Needs further investigation I guess. Debugging CI is complicated :(

**Comment by adambabik** [comment] 2023-03-06 21:51
The log is a bit tricky to follow up because the tests are run in parallel but I think this is a group:

```
2023-03-06T15:29:55.241Z	DEBUG	runner/service.go:301	sending data	{"_id": "cg30dso3digqu3rk1or0", "lenStdout": 46, "lenStderr": 0}
2023-03-06T15:29:55.242Z	DEBUG	runner/command.go:268	failed to copy from pty to stdout; handled EIO
2023-03-06T15:29:55.242Z	INFO	runner/service.go:317	command finished	{"_id": "cg30dso3digqu3rk1or0", "exitCode": 2}
```

The command finished with the exit code `2` but it had some output. Unfortunately, due to the test using `require.EqualValues(t, 0, result.ExitCode)` you didn't have a chance to see what the output is as it is checked in the next line. I recommend switching to:

```go
assert.EqualValues(t, 0, result.ExitCode)
assert.EqualValues(t, "24\r\n80\r\n", string(result.Stdout))
```

Overall, you can consider a few things:
- In the `Execute` method where `cfg := &commandConfig{ ... }` is instantiated, pass `Logger:      logger` instead of `Logger:      r.logger` so that the `command` struct logs also contain `_id`.
- On a branch, you can temporarily modify the line which execute tests (`run: SHELL=/bin/bash TZ=UTC go test ./...`) in `.github/workflows/ci.yml` to run only a single test with the `-run` option.

**Comment by mxsdev** [comment] 2023-03-07 16:53
Figured this out. Basically, the `tput` command requires to know the terminal name, which is usually stored in `$TERM`. CI doesn't do that though, so I just provided the variable `-T linux`. See #170

**Comment by adambabik** [comment] 2023-03-07 19:35
> Figured this out.

Was an error message in `stdout`?

**Comment by mxsdev** [comment] 2023-03-07 19:39
> Was an error message in stdout?

Yep. Gets sent by `tput` command.

**Closed** 2023-03-10 15:27 UTC
