### ISSUE TITLE
Document-level options "category"

### ISSUE THREAD

**Issue by ruzickap** [stateful/runme#580] opened 2024-05-19 20:07 UTC
Hello 

The new feature introduced in https://github.com/stateful/runme/issues/369 - 'Document-level options "category"' doesn't work:

Example - let's have the following file:

* `install-manual-solution-2.md`
<pre>
---
shell: bash
cwd: /tmp
category: solution-2
---

Installation steps for Solution 2:

```sh
echo "[1] Install command in $PWD"
```

```sh
echo "[2] Install second command"
```

```sh { "category":"delete-solution" }
echo "Delete solution"
```

```sh { "category":"delete-solution" }
echo "Delete solution - second command"
```
</pre>

* Issue 1 - If I run `runme run --all --skip-prompts --category solution-2 --dry-run` I got only first command in markdown document "processed":

  ```
  #!/opt/homebrew/bin/bash

  // run in "/tmp"

  set -e -o pipefail
  echo "[1] Install command in $PWD"
  ```

  -> Second command `[2] Install second command` is skipped / ignored ???

* Issue 2 - The `runme run --all --skip-prompts --category delete-solution --dry-run` is not working at all and `delete-solution` category is not "recognized":
  ```
  could not execute command: No tasks to execute with the category provided
  ```

It seems like the feature is buggy.

Thank you for looking at it...

**Comment by sourishkrout** [comment] 2024-05-20 13:28
Could you please verify/repro @pastuxso when you get a chance? Thanks.

**Comment by pastuxso** [comment] 2024-05-24 14:42
Hi @ruzickap, Thank you for reporting this issue. I'll review it and get back to you as soon as I have news.

**Comment by pastuxso** [comment] 2024-05-24 20:58
Hey @ruzickap, I've identified the cause of the issue and I'll fix it. In the meantime, you can use a workaround by adding a name to the cells you want to include in the global category and removing them from the cell with the category. Here's an example:


````md
---
shell: bash
cwd: /tmp
category: solution-2
---

Installation steps for Solution 2:

```sh {"name":"one"}
echo "[1] Install command in $PWD"
```

```sh {"name":"two"}
echo "[2] Install second command"
```

```sh {"category":"delete-solution"}
echo "Delete solution"
```

```sh {"category":"delete-solution"}
echo "Delete solution - second command"
```


````

**Comment by sourishkrout** [comment] 2024-06-03 14:55
@ruzickap apologies for the named vs unnamed oversight. We fixed the issue and added more test coverage. Thanks @pastuxso!

**Comment by pastuxso** [comment] 2024-06-03 22:04
@sourishkrout, that's excellent news. @ruzickap, I really appreciate your contribution and your patience on this.

**Comment by sourishkrout** [comment] 2024-06-04 18:22
Should be going into homebrew momentarily as soon as https://github.com/Homebrew/homebrew-core/pull/173683 is merged.

**Closed by sourishkrout** 2024-06-04 18:22 UTC
Labels: bug

**Comment by ruzickap** [comment] 2024-06-05 05:25
Thank you @pastuxso.

It seems like 'Document-level option "category"' is working fine :-)

As you mentioned above the `--dry-run` is showing only the first command:

```bash
❯ runme run --all --skip-prompts --category solution-2 --dry-run
#!/opt/homebrew/bin/bash

// run in "/tmp"

set -e -o pipefail
echo "[1] Install command in $PWD"
```

Let me create new issue for that to properly track it...

Thank you...

**Comment by sourishkrout** [comment] 2024-06-05 18:35
Thanks @ruzickap! We will keep you posted on #606 accordingly.
