### ISSUE TITLE
Runme doesn't load complete zsh profile

### ISSUE THREAD

**Issue by christian-bromann** [stateful/runme#221] opened 2023-04-19 01:18 UTC
Since `v1.0.1` Runme prints the following error messages for me:

```sh
/Users/christianbromann/.nvm/bash_completion:99: command not found: complete
/Users/christianbromann/.bin/google-cloud-sdk/completion.zsh.inc:37: command not found: complete
/Users/christianbromann/.bin/google-cloud-sdk/completion.zsh.inc:62: command not found: complete
/Users/christianbromann/.bin/google-cloud-sdk/completion.zsh.inc:63: command not found: complete
```

It seems like Runme doesn't load my whole zsh profile. Running `which complete` returns:

```sh
complete () {
        emulate -L zsh
        local args void cmd print remove
        args=("$@")
        zparseopts -D -a void o: A: G: W: C: F: P: S: X: a b c d e f g j k u v p=print r=remove
        if [[ -n $print ]]
        then
                printf 'complete %2$s %1$s\n' "${(@kv)_comps[(R)_bash*]#* }"
        elif [[ -n $remove ]]
        then
                for cmd
                do
                        unset "_comps[$cmd]"
                done
        else
                compdef _bash_complete\ ${(j. .)${(q)args[1,-1-$#]}} "$@"
        fi
}
```

**Comment by mxsdev** [comment] 2023-04-19 01:31
Can you trace from which file exactly that `complete` function gets defined?

**Comment by christian-bromann** [comment] 2023-04-19 02:55
In my `.zshrc` I have the following line:

```
# The next line enables shell command completion for gcloud.
if [ -f "$HOME/.bin/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/.bin/google-cloud-sdk/completion.zsh.inc"; fi
```

**Comment by sourishkrout** [comment] 2023-04-19 15:16
It really shouldn't be loading the `bash_completion` for `zsh`. That seems to be the root of the issue. @christian-bromann confirmed `runme` was installed out of homebrew-band.

If installed via homebrew, the stateful/tap/runme formula (https://github.com/stateful/homebrew-tap/blob/main/Formula/runme.rb#L28-L30) should take care of wiring this up for the respective shell.

I believe this is due to an inconsistent setup and shouldn't effect every runme CLI user.

Closing for now. Feel free to reopen if the problem crops again.

**Closed** 2023-04-19 15:17 UTC
