### ISSUE TITLE
Non-shell languages being stripped

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#73] opened 2022-12-08 16:17 UTC
Python code block in https://github.com/stateful/vscode-runme/blob/main/examples/README.md

![Image](https://user-images.githubusercontent.com/250527/206502196-1a4c6ed4-d1d8-4398-ab40-1312eaf03760.png)

The `readonly` (should be camel-case it?) would render the cell as type `markdown` instead of `code`.

**Comment by adambabik** [comment] 2022-12-08 16:59
@sourishkrout I presume it's a problem in the extension which converts code cells with an unsupported lang to markdown cells. At least [the current main](https://github.com/stateful/vscode-runme/blob/main/src/extension/notebook.ts#L129-L137) suggests that.

I run `./runme fmt --flatten "https://raw.githubusercontent.com/stateful/vscode-runme/main/examples/README.md"` and it prints the following:

````
## Non-Supported Languages

These are shown as simple markdowns, e.g:

```py {name=def-hello readonly=true}
def hello():
    print("Hello World")
```
````

**Comment by sourishkrout** [comment] 2022-12-08 17:17
Good point. I'll take a look.

**Comment by adambabik** [comment] 2022-12-09 09:48
@sourishkrout I tried https://github.com/stateful/vscode-runme/pull/81/commits/2169911c39f1a18af0592992f9840a44415dad9d and I cannot reproduce it. This is the diff after serialization:

````
 These are shown as simple markdowns, e.g:
 
-```py { readonly=true }
+```py {name=def-hello index=41 readonly=true}
 def hello():
-    print("Hello World")
+    print("Hello World CHANGED")
 ```
````

(After https://github.com/stateful/runme/pull/74 is merged, the code block attributes will be cleaner).

The code that you mentioned above is not used by the parser at all. It's only used by the CLI executor (`runme run`).

We have two options:
1. The deserializer always returns code blocks as code cells regardless whether a given language is supported or not. The extension would display them as code cells but disable execution. **It seems this is the current behaviour**.
2. The deserializer detects if a language is supported and converts code blocks with unsupported langs to markdown cells. In this case, the backticks would be kept intact. The problem is, I belive, that changing the lang to supported one would not change the cell display.

From the UX perspective, I think the option 1 is better.

**Comment by sourishkrout** [comment] 2022-12-09 21:20
@adambabik with the linked commit it will no longer strip the block since I removed the check whether or not execution is supported. There's unfortunately no such thing as disabling execution on a CODE cell which make 1.) impossible.

I do think 2.) is the better option for UX consistency. You can't change a MARKUP block to CODE, only the other way around.

**Closed as completed** 2022-12-13 14:27 UTC
